# fly.toml app configuration file generated for aflm-dev-lingering-firefly-6798 on 2025-02-16T11:08:05-08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'aflm-dev-lingering-firefly-6798'
primary_region = 'sea'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
