name: build-push-deploy

on:
  push:
    branches: [ main ]

  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      SERVICE: aflm-blog
      REGION: us-central1
    steps:
      - uses: actions/checkout@v2
      
      - name: setup cloud SDK
        uses: google-github-actions/setup-gcloud@v0.2.0
        with:
          project_id: ${{ secrets.PROJECT_ID }}
          service_account_key: ${{ secrets.SA_KEY }}
          export_default_credentials: true
      
      - name: authorize docker push
        run: gcloud auth configure-docker
#         env:
#           PROJECT_ID: ${{ secrets.PROJECT_ID  }}
#           SERVICE: aflm-blog
#           REGION: us-central1
      
      - name: build, push container
        run: |
          docker image build -f ./build/Dockerfile -t gcr.io/${{ secrets.PROJECT_ID }}/${{ env.SERVICE }}:${{ github.sha }} .
          docker push gcr.io/${{ secrets.PROJECT_ID }}/${{ env.SERVICE }}:${{ github.sha }}
      
      - name: deploy to Cloud Run
        id: deploy
        uses: google-github-actions/deploy-cloudrun@v0.2.0
        with:
          service: ${{ env.SERVICE }}
          image: gcr.io/${{ secrets.PROJECT_ID }}/${{ env.SERVICE }}:${{  github.sha }}
          region: ${{ env.REGION }}
