name: build-push-deploy

on:
  push:
    branches: [ main ]

jobs:
  build_test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-go@v4
      with:
        go-version-file: go.mod
    - run: go build

  deploy:
    runs-on: ubuntu-latest
    needs: build_test
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
    - uses: actions/checkout@v4
    - id: 'auth'
      uses: 'google-github-actions/auth@v2'
      with:
        workload_identity_provider: ${{ secrets.WID_PROVIDER }}
        service_account: ${{ secrets.DEPLOYER_SERVICE_ACCOUNT }}
    - name: 'setup cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v2'
    - name: 'authorize docker push'
      run: 'gcloud auth configure-docker us-central1-docker.pkg.dev'
    - name: 'build, push container'
      run: |
        docker image build -f Dockerfile -t us-central1-docker.pkg.dev/${{ secrets.PROJECT_ID }}/${{ secrets.ARTIFACT_REPOSITORY }}/blog:${{ github.sha }} .
        docker push us-central1-docker.pkg.dev/${{ secrets.PROJECT_ID }}/${{ secrets.ARTIFACT_REPOSITORY }}/blog:${{ github.sha }}
    - name: 'deploy to Cloud Run'
      run: |
        gcloud run deploy aflmdev \
          --image us-central1-docker.pkg.dev/${{ secrets.PROJECT_ID }}/${{ secrets.ARTIFACT_REPOSITORY }}/blog:${{ github.sha }} \
          --region us-central1 \
          --platform managed \
          --max-instances 1 \
          --port 443 \
          --service-account ${{ secrets.RUNTIME_SERVICE_ACCOUNT }} \
          --allow-unauthenticated
