name: build-push-deploy

on:
  push:
    branches: [ main ]

  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: setup cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.PROJECT_ID }}
          service_account_key: ${{ secrets.SA_KEY }}
          export_default_credentials: true
      
      - name: authorize docker push
        run: gcloud auth configure-docker
      
      - name: build, push container
        run: |
          docker image build -f Dockerfile -t gcr.io/${{ secrets.PROJECT_ID }}/${{ github.repository }}:${{ github.sha }} .
          docker push gcr.io/${{ secrets.PROJECT_ID }}/${{ github.repository }}:${{ github.sha }}
      
      - name: deploy to Cloud Run
        run: |
          gcloud run deploy aflmdev \
            --image gcr.io/${{ secrets.PROJECT_ID }}/${{ github.repository }}:${{  github.sha }} \
            --region us-central1 \
            --platform managed \
            --max-instances 1 \
            --port 443 \
            --allow-unauthenticated
            
        # id: deploy
        # uses: google-github-actions/deploy-cloudrun@v0.2.0
        # with:
        #   service: aflm-blog
        #   image: gcr.io/${{ secrets.PROJECT_ID }}/${{ github.repository }}:${{  github.sha }}
        #   region: ${{ env.REGION }}
        #   env_vars: PORT=443
            
